// Package recipe emits the Linux image recipe and build context for a prepared
// runnable. The agent never runs a container build: it describes one, and the
// CLI's image executor builds and publishes it (codefly-dev/core#461).
package recipe

import (
	"encoding/json"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/codefly-dev/core/resources"

	"github.com/codefly-dev/runnable-python/pkg/prepare"
)

// Schema versions the recipe document the image executor reads.
const Schema = "codefly.runnable-image-recipe/v1"

// Names of what a recipe emits into its output directory.
const (
	DockerfileName = "Dockerfile"
	RecipeFile     = "image-recipe.json"
)

// UVVersion pins the dependency installer copied into the build stage. The
// image resolves nothing: it installs the same hashed requirements the native
// package was prepared from.
const UVVersion = "0.12.13"

// WorkDirectory is where the recipe places the runnable inside the image.
const WorkDirectory = "/app"

// Recipe is what the CLI's image executor needs to build the Linux artifact.
type Recipe struct {
	Schema     string   `json:"schema"`
	Dockerfile string   `json:"dockerfile"`
	Context    string   `json:"context"`
	Platforms  []string `json:"platforms"`
	Entrypoint []string `json:"entrypoint"`
	Toolchain  string   `json:"toolchain"`
}

// Platforms are the Linux platforms the recipe supports.
var Platforms = []string{"linux/amd64", "linux/arm64"}

// Write emits the build context and the recipe describing it. The context is
// the prepared tree without its native environment: an interpreter prepared on
// the build host is not the one the image runs.
func Write(runnable *resources.Runnable, prepared *prepare.Prepared, directory string) (*Recipe, error) {
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return nil, err
	}
	if err := copyContext(prepared.Root, directory); err != nil {
		return nil, fmt.Errorf("copy image context: %w", err)
	}
	version := prepare.PythonVersion(runnable)
	dockerfile := dockerfile(version)
	if err := os.WriteFile(filepath.Join(directory, DockerfileName), dockerfile, 0o644); err != nil {
		return nil, err
	}
	recipe := &Recipe{
		Schema:     Schema,
		Dockerfile: DockerfileName,
		Context:    ".",
		Platforms:  Platforms,
		Entrypoint: []string{
			filepath.Join(WorkDirectory, prepare.Environment, "bin", "python"),
			filepath.Join(WorkDirectory, prepare.EntryFile),
		},
		Toolchain: "python-" + version,
	}
	encoded, err := json.MarshalIndent(recipe, "", "  ")
	if err != nil {
		return nil, err
	}
	if err := os.WriteFile(filepath.Join(directory, RecipeFile), append(encoded, '\n'), 0o644); err != nil {
		return nil, err
	}
	return recipe, nil
}

func dockerfile(version string) []byte {
	var out strings.Builder
	fmt.Fprintf(&out, `# syntax=docker/dockerfile:1
# Generated by runnable-python. The image installs the same hashed
# requirements the native package was prepared from.
FROM python:%s-slim AS build
COPY --from=ghcr.io/astral-sh/uv:%s /uv /usr/local/bin/uv
WORKDIR %s
COPY %s ./
RUN uv venv --relocatable --python python3 %s \
 && uv pip install --python %s/bin/python --require-hashes -r %s
COPY %s ./%s
COPY %s ./

FROM python:%s-slim
WORKDIR %s
COPY --from=build %s %s
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
USER 65532:65532
ENTRYPOINT ["%s/%s/bin/python", "%s/%s"]
`,
		version, UVVersion, WorkDirectory,
		prepare.RequirementsFile,
		prepare.Environment, prepare.Environment, prepare.RequirementsFile,
		prepare.SourceDirectory, prepare.SourceDirectory,
		prepare.EntryFile,
		version, WorkDirectory, WorkDirectory, WorkDirectory,
		WorkDirectory, prepare.Environment, WorkDirectory, prepare.EntryFile,
	)
	return []byte(out.String())
}

func copyContext(root string, directory string) error {
	return filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		if relative == "." {
			return nil
		}
		if entry.IsDir() && entry.Name() == prepare.Environment {
			return filepath.SkipDir
		}
		destination := filepath.Join(directory, relative)
		if entry.IsDir() {
			return os.MkdirAll(destination, 0o755)
		}
		from, err := os.Open(path)
		if err != nil {
			return err
		}
		defer from.Close()
		to, err := os.Create(destination)
		if err != nil {
			return err
		}
		defer to.Close()
		_, err = io.Copy(to, from)
		return err
	})
}
